namespace autoCardboard.Pandemic.Domain
{
    public enum City
    {
        [Disease(Disease.Blue)]
        Atlanta,
        [Disease(Disease.Blue)]
        Chicago,
        [Disease(Disease.Blue)]
        Essen,
        [Disease(Disease.Blue)]
        London,
        [Disease(Disease.Blue)]
        Madrid,
        [Disease(Disease.Blue)]
        Milan,
        [Disease(Disease.Blue)]
        Montreal,
        [Disease(Disease.Blue)]
        NewYork,
        [Disease(Disease.Blue)]
        Paris,
        [Disease(Disease.Blue)]
        SanFrancisco,
        [Disease(Disease.Blue)]
        StPetersburg,
        [Disease(Disease.Blue)]
        Washington,
        [Disease(Disease.Yellow)]
        Bogota,
        [Disease(Disease.Yellow)]
        BuenosAires,
        [Disease(Disease.Yellow)]
        Johannesburg,
        [Disease(Disease.Yellow)]
        Khartoum,
        [Disease(Disease.Yellow)]
        Kinshasa,
        [Disease(Disease.Yellow)]
        Lagos,
        [Disease(Disease.Yellow)]
        Lima,
        [Disease(Disease.Yellow)]
        LosAngeles,
        [Disease(Disease.Yellow)]
        MexicoCity,
        [Disease(Disease.Yellow)]
        Miami,
        [Disease(Disease.Yellow)]
        Santiago,
        [Disease(Disease.Yellow)]
        SaoPaulo,

        [Disease(Disease.Black)]
        Algiers,
        [Disease(Disease.Black)]
        Baghdad,
        [Disease(Disease.Black)]
        Cairo,
        [Disease(Disease.Black)]
        Chennai,
        [Disease(Disease.Black)]
        Delhi,
        [Disease(Disease.Black)]
        Istanbul,
        [Disease(Disease.Black)]
        Karachi,
        [Disease(Disease.Black)]
        Kolkata,
        [Disease(Disease.Black)]
        Moscow,
        [Disease(Disease.Black)]
        Mumbai,
        [Disease(Disease.Black)]
        Riyadh,
        [Disease(Disease.Black)]
        Tehran,
        [Disease(Disease.Red)]
        Bangkok,
        [Disease(Disease.Red)]
        Beijing,
        [Disease(Disease.Red)]
        HoChiMinhCity,
        [Disease(Disease.Red)]
        HongKong,
        [Disease(Disease.Red)]
        Jakarta,
        [Disease(Disease.Red)]
        Manila,
        [Disease(Disease.Red)]
        Osaka,
        [Disease(Disease.Red)]
        Seoul,
        [Disease(Disease.Red)]
        Shanghai,
        [Disease(Disease.Red)]
        Sydney,
        [Disease(Disease.Red)]
        Taipei,
        [Disease(Disease.Red)]
        Tokyo
    }
}
